exports.languageLabels = {
  english: {
    transmMaxTemp: "Max Transmitter Temp",
    transmMinTemp: "Min Transmitter Temp",
    maxDesirTemp: "Max Desirable Temp",
    minDesirTemp: "Min Desirable Temp",
    setPoint: "Set Point",
    sensitivity: "Sensitivity",
    currTemp: "Current Temperature",
    maxFinContPress: "Max Final Control Press",
    minFinContPress: "Min Final Control Press",
    pressure: "Pressure",
    temperature: "Temperature",
    changeOptions: "Toggle buttons to change",
    normalOpen: "Normally open",
    normalClosed: "Normally closed",
    proportBand:"Proportional Band",
    transmPress: "Transmitter pressure",
    finContrPress: "Final control pressure",
    openFinContr: "% open final control",
    transmTempRange:'Transmitter temp range',
    transmPressRange:'Transmitter press range',
    finalControlPressRange: 'Final control press range',
    finalControlOpenRange:'Final control openness range'
  },
  french: {
    transmMaxTemp: "Max Temp Transmetteur",
    transmMinTemp: "Min Temp Transmetteur",
    maxDesirTemp: "Max Temp Desirable",
    minDesirTemp: "Min Temp Desirable",
    setPoint: "Point de consigne",
    sensitivity: "Sensitivité",
    currTemp: "Temperature",
    maxFinContPress: "Max Press Contrôle Final",
    minFinContPress: "Min Press Contrôle Final",
    pressure: "Pression",
    temperature: "Temperature",
    changeOptions: "Cliquez les boutons pour changer les options",
    normalOpen: "Normallement ouvert",
    normalClosed: "Normallement fermé",
    proportBand: "Bande proportionnelle",
    transmPress: "Pression transmetteur",
    finContrPress: 'Pression contrôle final',
    openFinContr: '% ouvert contrôle final',
    openFinContr: "% open final control",
    transmTempRange:'Rangée temp transmetteur',
    transmPressRange:'Rangée press transmetteur',
    finalControlPressRange: 'Rangée press contrôle final',
    finalControlOpenRange:'Rangée ouverture contrôle final'
  }
};